Sage-Bionetworks/portals

- app-template/package.json
- app-template/src/Footer.tsx
- app-template/src/types/portal-config.d.ts
- app-template/yarn.lock
- configurations/amp-ad/footerConfig.ts
- configurations/amp-ad/scripts/exportS3ProductionBucketName.sh
- configurations/amp-ad/scripts/exportS3StagingBucketName.sh
Added bucket names
Bumped SRC
Added forum link to footer
> Add bucket names for amp-ad

- app-template/package.json
- app-template/src/App.scss
- app-template/src/example-configuration/loadingScreen.tsx
- app-template/yarn.lock
- configurations/amp-ad/loadingScreen.tsx
- configurations/amp-ad/synapseConfigs/programs.ts
- configurations/amp-ad/synapseConfigs/programs/amp-ad.ts
- configurations/amp-ad/synapseConfigs/programs/model-ad.ts
- configurations/amp-ad/synapseConfigs/programs/move2-ad.ts
- configurations/amp-ad/synapseConfigs/programs/resilience-ad.ts
- configurations/config-shell/loadingScreen.tsx
- configurations/csbc-pson/routesConfig.ts
- configurations/nf/loadingScreen.tsx
- configurations/nf/routesConfig.ts
- configurations/package.json
Small UI fixes, fixed homepage header view all button z-index so it doesn't get overlapped
> Bumped SRC and changed props accordingly

- app-template/package.json
- app-template/public/index.html
- app-template/src/App.scss
- app-template/src/AppInitializer.tsx
- app-template/yarn.lock
- configurations/package.json
SWC-4827 - Add pendo to portal
PORTALS-504 - SRC bump fixes this issue
> SWC-4827 and PORTALS-504

- app-template/package.json
- app-template/yarn.lock
- configurations/amp-ad/routesConfig.ts
- configurations/amp-ad/synapseConfigs/projects.ts
- configurations/package.json
- configurations/yarn.lock
Bump SRC and add props to configure project page routing
> PORTALS-478

- app-template/package.json
- app-template/public/index.html
- app-template/src/RouteResolver.tsx
- app-template/src/example-configuration/exploreHomeConfiguration/data.ts
- app-template/src/example-configuration/exploreHomeConfiguration/publications.ts
- app-template/src/portal-components/ExploreButtonControlWrapper.tsx
- app-template/yarn.lock
- configurations/amp-ad/synapseConfigs/data.ts
- configurations/amp-ad/synapseConfigs/people.ts
- configurations/amp-ad/synapseConfigs/programs/amp-ad.ts
- configurations/amp-ad/synapseConfigs/programs/model-ad.ts
- configurations/amp-ad/synapseConfigs/programs/move2-ad.ts
- configurations/amp-ad/synapseConfigs/programs/resilience-ad.ts
- configurations/amp-ad/synapseConfigs/projects.ts
- configurations/amp-ad/synapseConfigs/studies.ts
- configurations/nf/synapseConfigs/data.ts
- configurations/nf/synapseConfigs/datasets.ts
- configurations/nf/synapseConfigs/files.ts
- configurations/nf/synapseConfigs/publications.ts
- configurations/nf/synapseConfigs/studies.ts
- configurations/package.json
Fixes - 
PORTALS-478 - fixes failed query
PORTALS-544 - portal project page linking on program pages
PORTALS-545 google analytics
> PORTALS-478, PORTALS-544, PORTALS-545

- configurations/nf/synapseConfigs/publications.ts
- configurations/nf/synapseConfigs/studies.ts
mostly data entry, updated facet aliases accordingly, fixed a duplicated key
> PORTALS-548

- app-template/package.json
- app-template/src/RouteResolver.tsx
- app-template/src/example-configuration/routesConfig.ts
- app-template/src/tests/RouterResolver.test.tsx
- configurations/amp-ad/style/_overides.scss
- configurations/amp-ad/synapseConfigs/publications.ts
- configurations/nf/synapseConfigs/organizationConfigs/dhart-spore.ts
- configurations/nf/synapseConfigs/organizationConfigs/generateConfig.ts
- configurations/nf/synapseConfigs/organizationConfigs/ntap.ts
- configurations/package.json
-Last UI tweaks for NF organization pages -- added QueryCount component to button wrapper so count displays correctly on the page, added additional prop so the count would work
-Added publications card for AMP-AD
-Bump SRC
- changed filename for consistency
> PORTALS-547, PORTALS-513

- app-template/package.json
- app-template/yarn.lock
- configurations/nf/routeButtonControlWrapperProps.ts
- configurations/nf/routesConfig.ts
- configurations/nf/synapseConfigs/datasets.ts
- configurations/nf/synapseConfigs/files.ts
- configurations/nf/synapseConfigs/organizationConfigs/ctf.ts
- configurations/nf/synapseConfigs/organizationConfigs/dhart-spore.ts
- configurations/nf/synapseConfigs/organizationConfigs/generateConfig.ts
- configurations/nf/synapseConfigs/organizationConfigs/ntap.ts
- configurations/nf/synapseConfigs/studies.ts
- configurations/package.json
- configurations/yarn.lock
Adds programmatic study pages to NF
Also rearranged keys for NF
Bump from SRC should fix query counts
> PORTALS-443, PORTALS 513, PORTALS-567

- app-template/package.json
- app-template/src/portal-components/Layout.tsx
- configurations/amp-ad/routesConfig.ts
- configurations/nf/routesConfig.ts
- configurations/package.json
Fixes: PORTALS-569, PORTALS-570, PORTALS-568, PORTALS-443
> Bump SRC and update config files for AMP and NF

- app-template/package.json
- app-template/src/Markdown.scss
- app-template/yarn.lock
- configurations/package.json
- configurations/yarn.lock
SRC update also fixes PORTALS-712, PORTALS-714, PORTALS-715, and PORTALS-716
> PORTALS-700

- app-template/package.json
- app-template/src/RouteResolver.tsx
- app-template/src/types/portal-config.d.ts
- app-template/yarn.lock
- configurations/drug-nomiation-tool/routesConfig.ts
- configurations/package.json
- configurations/yarn.lock
Added drug nomination tool to portal
TODO: drug nomination tool will need its props updated with the production schemas
> PORTALS-720

- app-template/src/App.scss
- app-template/src/Header.tsx
- app-template/src/Navbar.tsx
- app-template/src/portal-components/GenerateComponentsFromRow.scss
- app-template/src/portal-components/GenerateComponentsFromRow.tsx
- configurations/amp-ad/routesConfig.ts
- configurations/amp-ad/synapseConfigs/results.ts
- configurations/amp-ad/synapseConfigs/studies.ts
- configurations/drug-nomiation-tool/scripts/exportS3ProductionBucketName.sh
- configurations/drug-nomiation-tool/scripts/exportS3StagingBucketName.sh
PORTALS-695, PORTALS-675, PORTALS-693, PORTALS-680, PORTALS-676, PORTALS-698, PORTALS-677
> PORTALS-721

- app-template/package.json
- app-template/src/App.scss
- app-template/src/Markdown.scss
- app-template/yarn.lock
- configurations/amp-ad/routeButtonControlWrapperProps.ts
- configurations/amp-ad/routesConfig.ts
- configurations/amp-ad/synapseConfigs/people.ts
- configurations/amp-ad/synapseConfigs/studies.ts
- configurations/package.json
- configurations/yarn.lock
PORTALS-685, PORTALS-688, PORTALS-719, PORTALS-717, PORTALS-726
> Bump SRC & UI Tweaks

- app-template/package.json
- app-template/src/App.scss
- app-template/src/AppInitializer.tsx
- app-template/src/Markdown.scss
- app-template/yarn.lock
- configurations/drug-nomiation-tool/footerConfig.ts
- configurations/drug-nomiation-tool/routesConfig.ts
- configurations/package.json
PORTALS-762 - added route for contact us page to drug nomination tool
PORTALS-679 - added styling for whats new section to markdown scss file
PORTALS-717 -  override default text color
> PORTALS-762, PORTALS-679, PORTALS-717

- app-template/package.json
- configurations/drug-nomiation-tool/routesConfig.ts
- configurations/package.json
- configurations/yarn.lock
There was another package.json that needed a version bump in app-templates
> fix bump version in app-templates

- app-template/package.json
- app-template/yarn.lock
- configurations/package.json
- configurations/yarn.lock
> chore(SRC): version bump to .68

- app-template/yarn.lock
- configurations/adknowledgeportal/betaBannerConfig.ts
- configurations/stopadportal/docTitleConfig.ts
- configurations/stopadportal/headerConfig.ts
- configurations/stopadportal/logoHeaderConfig.ts
PORTALS-815, PORTALS-830 - updates to the document title, home page header, and navbar title.
PORTALS-778 - empty beta banner config for amp
> PORTALS-815, PORTALS-830, PORTALS-778

- configurations/stopadportal/routesConfig.ts
> fix(CNT): add class to fileGrid

- configurations/nf/routesConfig.ts
PORTALS-651 - Aliasing for NF study cards
> PORTALS-651

- app-template/package.json
- app-template/yarn.lock
- configurations/package.json
- configurations/yarn.lock
please update staging if merged.
> bump src to 1.12.71

- app-template/src/App.scss
- app-template/src/RouteResolver.tsx
- app-template/src/portal-components/Layout.tsx
- app-template/src/portal-components/StatefulButtonControlWrapper.tsx
- app-template/src/types/portal-config.d.ts
- configurations/adknowledgeportal/routesConfig.ts
- configurations/csbc-pson/routesConfig.ts
- configurations/nf/routesConfig.ts
* PORTALS-852 - added class to home page explore object on each portal except drug tool (doesn't have the component) which adds a gray background and padding
* Formatting from linter
> PORTALS-852

- app-template/package.json
- app-template/src/App.scss
- app-template/yarn.lock
- configurations/adknowledgeportal/synapseConfigs/projects.ts
- configurations/adknowledgeportal/synapseConfigs/studies.ts
- configurations/csbc-pson/routesConfig.ts
- configurations/csbc-pson/synapseConfigs/datasets.ts
- configurations/csbc-pson/synapseConfigs/publications.ts
- configurations/csbc-pson/synapseConfigs/studies.ts
- configurations/nf/routesConfig.ts
- configurations/nf/synapseConfigs/studies.ts
- configurations/package.json
- configurations/yarn.lock
* PORTALS-860 - updated sql for studies
* Updated props
* PORTALS-622 -made it so nav and footer don't print
> PORTALS-816

- configurations/csbc-pson/routesConfig.ts
- configurations/csbc-pson/synapseConfigs/datasets.ts
- configurations/csbc-pson/synapseConfigs/publications.ts
- configurations/csbc-pson/synapseConfigs/studies.ts
- configurations/nf/synapseConfigs/publications.ts
Fixed prop name: LabelLink -> LabelConfig
Added a link from nf publication cards -> studies
> PORTALS-189, PORTALS-893

- configurations/csbc-pson/headerConfig.ts
- configurations/csbc-pson/synapseConfigs/commonProps.ts
- configurations/csbc-pson/synapseConfigs/datasets.ts
- configurations/csbc-pson/synapseConfigs/files.ts
- configurations/csbc-pson/synapseConfigs/grants.ts
- configurations/csbc-pson/synapseConfigs/publications.ts
- configurations/csbc-pson/synapseConfigs/studies.ts
- configurations/csbc-pson/synapseConfigs/tools.ts
PORTALS-657
PORTALS-912, PORTALS-913
PORTALS-901, partial PORTALS-897
PORTALS-917
> CSBC Fixes

- app-template/package.json
- app-template/src/AppInitializer.tsx
- app-template/src/portal-components/QueryWrapperFlattened.tsx
- app-template/src/test-configuration/exploreHomeConfiguration/publications.ts
- app-template/src/test-configuration/exploreHomeConfiguration/studies.ts
- app-template/src/types/portal-config.d.ts
- app-template/yarn.lock
- configurations/adknowledgeportal/synapseConfigs/data.ts
- configurations/adknowledgeportal/synapseConfigs/people.ts
- configurations/adknowledgeportal/synapseConfigs/projects.ts
- configurations/adknowledgeportal/synapseConfigs/publications.ts
- configurations/adknowledgeportal/synapseConfigs/studies.ts
- configurations/adknowledgeportal/synapseConfigs/tools.ts
- configurations/csbc-pson/routesConfig.ts
- configurations/csbc-pson/synapseConfigs/commonProps.ts
- configurations/csbc-pson/synapseConfigs/datasets.ts
- configurations/csbc-pson/synapseConfigs/files.ts
- configurations/csbc-pson/synapseConfigs/grants.ts
- configurations/csbc-pson/synapseConfigs/publications.ts
- configurations/csbc-pson/synapseConfigs/studies.ts
- configurations/csbc-pson/synapseConfigs/tools.ts
- configurations/nf/synapseConfigs/datasets.ts
- configurations/nf/synapseConfigs/files.ts
- configurations/nf/synapseConfigs/organizationConfigs/generateConfig.ts
- configurations/nf/synapseConfigs/publications.ts
- configurations/nf/synapseConfigs/studies.ts
- configurations/nf/synapseConfigs/tools.ts
- configurations/package.json
- configurations/stopadportal/routesConfig.ts
PORTALS-920, PORTALS-921, PORTALS-921
> Bump SRC, CSBC Issues

- configurations/csbc-pson/routesConfig.ts
- configurations/csbc-pson/synapseConfigs/commonProps.ts
- configurations/csbc-pson/synapseConfigs/datasets.ts
- configurations/csbc-pson/synapseConfigs/grants.ts
- configurations/csbc-pson/synapseConfigs/publications.ts
- configurations/csbc-pson/synapseConfigs/studies.ts
made one source of truth for links, added grant details page and grant detail page links
> PORTALS-914, PORTALS-915, PORTALS-916

- app-template/package.json
- configurations/csbc-pson/synapseConfigs/grants.ts
- configurations/nf/synapseConfigs/organizationConfigs/cdmrp.ts
- configurations/package.json
Bumping SRC fixes the following - 
PORTALS-964
PORTALS-785
Also removed unused values in cdmrp.ts file
> PORTALS-964 PORTALS-785

- app-template/src/App.scss
- app-template/src/Header.tsx
- app-template/yarn.lock
- configurations/adknowledgeportal/routesConfig.ts
- configurations/csbc-pson/routesConfig.ts
- configurations/nf/routesConfig.ts
removes gray background and fixes header width to be full screen
> PORTALS-967, PORTALS-965

- src/configurations/nf/synapseConfigs/organizationConfigs/cdmrp.ts
- src/configurations/nf/synapseConfigs/organizationConfigs/dhart-spore.ts
> PORTALS-969

- src/configurations/csbc-pson/synapseConfigs/commonProps.ts
- src/configurations/csbc-pson/synapseConfigs/tools.ts
Make PublicationtTitle render as markdown, and also alias projectId column
> PORTALS-979: add alias for projectid

- src/Footer.tsx
- src/portal-components/Versions.scss
- src/portal-components/Versions.tsx
since this will catch the majority of changes
> PORTALS-349: expose SRC version only

- package.json
- src/configurations/adknowledgeportal/routesConfig.ts
- src/configurations/adknowledgeportal/synapseConfigs/news.ts
TODO: update synapse-react-client to use version that includes changes from https://github.com/Sage-Bionetworks/Synapse-React-Client/pull/357
> PORTALS-987

- src/configurations/nf/routesConfig.ts
- src/configurations/nf/synapseConfigs/organizationConfigs/gff.ts
Added route for GFF foundation
Removed limit on organization home page cards that was cutting of the rest of the funders
> PORTALS-1001/1002

- src/Navbar.scss
- src/Navbar.tsx
perhaps the crawler was iterating through the visible elements on the page?
> PORTALS-775: try full url hrefs, and a different method of hiding the links

- package.json
- sitemap/generate-sitemap.js
- src/App.tsx
- src/AppInitializer.tsx
- src/Navbar.tsx
- src/configurations/stopadportal/footerConfig.ts
- src/configurations/stopadportal/routesConfig.ts
- yarn.lock
TODO
- update SRC
- deploy to a staging portal bucket.  
- update staging portal bucket settings, and cloudfront distribution (this will eventually need to be done on 7 other buckets, if successful)
> PORTALS-775: use standard router instead of hash-based

- src/configurations/adknowledgeportal/routesConfig.ts
- src/configurations/adknowledgeportal/synapseConfigs/data.ts
to attempt to add to the Google index, and other fixes
> hide contribute and HasAccess column so that we can release amp-ad

- public/robots.txt
(varies depending on staging vs prod)
> remove robots.txt from portals output, should be part of bucket init

- src/App.scss
- src/Navbar.tsx
- src/configurations/adknowledgeportal/routesConfig.ts
Added route for Data Use Certificates
Used Link instead of href to avoid page refresh in navbar dropdown
> PORTALS-1026

- src/configurations/csbc-pson/routesConfig.ts
- src/configurations/csbc-pson/style/_overides.scss
- src/portal-components/csbc-home-page/Ecosystem.tsx
- src/portal-components/csbc-home-page/HomePageLinks.tsx
- src/portal-components/csbc-home-page/style/_ecosystem.scss
- src/portal-components/csbc-home-page/style/_home-page-links.scss
> Add ecosystem section

- package.json
- src/configurations/csbc-pson/routesConfig.ts
- src/configurations/csbc-pson/synapseConfigs/onPointClick.ts
- src/configurations/csbc-pson/synapseConfigs/publications.ts
- src/configurations/csbc-pson/synapseConfigs/tools.ts
- src/portal-components/csbc-home-page/style/_ecosystem.scss
- yarn.lock
bump src
update props for themesplot
switch to multi value tools/publications tables
update click handler
put in wikis for home page ecosystem
> PORTALS-1082

- src/configurations/nf/routesConfig.ts
- src/configurations/nf/synapseConfigs/publications.ts
- src/configurations/nf/synapseConfigs/studies.ts
- src/portal-components/GenerateComponentsFromRow.scss
- src/portal-components/GenerateComponentsFromRow.tsx
- src/portal-components/QueryWrapperFlattened.tsx
- src/portal-components/injectPropsIntoConfig.ts
- src/tests/portal-components/GenerateComponentsFromRow.test.tsx
- src/tests/portal-components/injectPropsIntoConfig.test.ts
- src/types/portal-util-types.ts
Added study details page configuration
> PORTALS-1013

- package.json
- src/Navbar.tsx
- src/configurations/adknowledgeportal/headerConfig.ts
- src/configurations/adknowledgeportal/headerConfig.tsx
- yarn.lock
Merging this is for now although it has failing tests, they do pass locally. Justifying this because the current staging amp-ad site has on the order of 4x as many API calls as it should.
> PORTALS-1103

- src/Navbar.tsx
- src/configurations/adknowledgeportal/synapseConfigs/data.ts
> Add download list and download from table to portals

- src/configurations/bsmn/synapseConfigs/projects.ts
I have not changed the underlying table schema, will do so after this merges.
> PORTALS-1219 change institutions to institution

- src/configurations/csbc-pson/synapseConfigs/datasets.ts
- src/configurations/csbc-pson/synapseConfigs/grants.ts
- src/configurations/csbc-pson/synapseConfigs/publications.ts
- src/configurations/csbc-pson/synapseConfigs/tools.ts
Pointing to latest merged tables in CSBC/PS-ON Synapse project, with updates to column names based on the current schemas.
> update schema/config for csbc/pson grants, datasets, pubs, tools

- package.json
- src/configurations/csbc-pson/routesConfig.ts
- src/configurations/csbc-pson/synapseConfigs/grants.ts
- yarn.lock
From SRC Bump
---
[PORTALS-1240](https://sagebionetworks.jira.com/browse/PORTALS-1240)
[PORTALS-1242](https://sagebionetworks.jira.com/browse/PORTALS-1242)
[PORTALS-1243](https://sagebionetworks.jira.com/browse/PORTALS-1243) 
[PORTALS-1246](https://sagebionetworks.jira.com/browse/PORTALS-1246)
From portal config change
---
[PORTALS-1251](https://sagebionetworks.jira.com/browse/PORTALS-1251)
[PORTALS-1252](https://sagebionetworks.jira.com/browse/PORTALS-1252)
> PORTALS-1251/1252, bump SRC

- src/configurations/bsmn/synapseConfigs/publications.ts
- src/configurations/bsmn/synapseConfigs/studies.ts
- src/configurations/bsmn/synapseConfigs/tools.ts
Left out people and projects until they have facets
> PORTALS-1299

- package.json
- src/App.tsx
- src/configurations/digitalhealth/routesConfig.ts
- src/configurations/digitalhealth/style/_overides.scss
- src/configurations/digitalhealth/synapseConfigs/data.ts
- src/configurations/digitalhealth/synapseConfigs/projects.ts
- src/configurations/digitalhealth/synapseConfigs/studies.ts
- src/portal-components/injectPropsIntoConfig.ts
Solved - https://sagebionetworks.jira.com/browse/PORTALS-1016
Also fixes small config issues with digital health
> added support for wikis on detail pages with wikiId set

- src/configurations/digitalhealth/routeButtonControlWrapperProps.ts
- src/configurations/digitalhealth/routesConfig.ts
- src/configurations/digitalhealth/style/_overides.scss
- src/configurations/digitalhealth/synapseConfigs/data.ts
- src/configurations/digitalhealth/synapseConfigs/projects.ts
- src/configurations/digitalhealth/synapseConfigs/publications.ts
- src/configurations/digitalhealth/synapseConfigs/studies.ts
- src/configurations/digitalhealth/synapseConfigs/tools.ts
Refactored detail page components, export detail page configs from each explore page.
> PORTALS-1358/1359/1361/1363/1366

- src/configurations/csbc-pson/docTitleConfig.ts
- src/configurations/csbc-pson/headerConfig.tsx
- src/configurations/csbc-pson/logoFooterConfig.ts
- src/configurations/csbc-pson/logoHeaderConfig.ts
- src/configurations/csbc-pson/routesConfig.ts
Replace headers and labels to use "Cancer Complexity Knowledge Portal"
> update portal name

- src/RouteResolver.tsx
- src/configurations/adknowledgeportal/routeButtonControlWrapperProps.ts
- src/configurations/adknowledgeportal/routesConfig.ts
- src/configurations/bsmn/routeButtonControlWrapperProps.ts
- src/configurations/bsmn/routesConfig.ts
- src/configurations/crc-researcher/routeButtonControlWrapperProps.ts
- src/configurations/crc-researcher/routesConfig.ts
- src/configurations/csbc-pson/routeButtonControlWrapperProps.ts
- src/configurations/csbc-pson/routesConfig.ts
- src/configurations/digitalhealth/routeButtonControlWrapperProps.ts
- src/configurations/digitalhealth/routesConfig.ts
- src/configurations/nf/routeButtonControlWrapperProps.ts
- src/configurations/nf/routesConfig.ts
- src/configurations/nf/synapseConfigs/files.ts
- src/configurations/nf/synapseConfigs/organizationConfigs/cdmrp.ts
- src/configurations/nf/synapseConfigs/organizationConfigs/ctf.ts
- src/configurations/nf/synapseConfigs/organizationConfigs/dhart-spore.ts
- src/configurations/nf/synapseConfigs/organizationConfigs/generateConfig.ts
- src/configurations/nf/synapseConfigs/organizationConfigs/gff.ts
- src/configurations/nf/synapseConfigs/organizationConfigs/nfri.ts
- src/configurations/nf/synapseConfigs/organizationConfigs/ntap.ts
- src/configurations/nf/synapseConfigs/studies.ts
- src/configurations/psychencode/routeButtonControlWrapperProps.ts
- src/configurations/psychencode/routesConfig.ts
- src/portal-components/RouteButtonControlWrapper.tsx
- src/portal-components/StatefulButtonControlWrapper.tsx
- src/test-configuration/routesConfig.ts
- src/types/portal-config.ts
Add new organization page
Simplified logic for org pages
Fixed props for SynapseObject and reflected that in each portal
> PORTALS-945

- src/configurations/cancercomplexity/betaBannerConfig.ts
- src/configurations/cancercomplexity/docTitleConfig.ts
- src/configurations/cancercomplexity/footerConfig.ts
- src/configurations/cancercomplexity/headerConfig.ts
- src/configurations/cancercomplexity/loadingScreen.tsx
- src/configurations/cancercomplexity/logoFooterConfig.ts
- src/configurations/cancercomplexity/logoHeaderConfig.ts
- src/configurations/cancercomplexity/routesConfig.ts
- src/configurations/cancercomplexity/scripts/exportS3ProductionBucketName.sh
- src/configurations/cancercomplexity/scripts/exportS3StagingBucketName.sh
- src/configurations/cancercomplexity/style/_overides.scss
- src/configurations/cancercomplexity/synapseConfigs/index.ts
[portals-1391]
Init. Copied from config-shell, only changed scripts/*.
> PORTALS-1391

- src/configurations/cancercomplexity/facetAliases.ts
- src/configurations/cancercomplexity/synapseConfigs/datasets.ts
- src/configurations/cancercomplexity/synapseConfigs/files.ts
- src/configurations/cancercomplexity/synapseConfigs/grants.ts
- src/configurations/cancercomplexity/synapseConfigs/publications.ts
- src/configurations/cancercomplexity/synapseConfigs/tools.ts
See: https://sagebionetworks.jira.com/browse/PORTALS-1389
> Config search fields for Cancer Complexity explore pages

- src/configurations/psychencode/docTitleConfig.ts
- src/configurations/psychencode/headerConfig.ts
Two small fixes to the banner on the homepage. 
As I am unfamiliar with this code base this may not be the right fix - I'm interested in helping where I can.
> fix spelling homepage

- package.json
- src/portal-components/GenerateComponentsFromRow.scss
- src/portal-components/GenerateComponentsFromRow.tsx
- src/react-app-env.d.ts
- yarn.lock
When no data will show the following -
> PORTALS-1404: handle empty details page

- src/configurations/cancercomplexity/routesConfig.ts
See https://sagebionetworks.jira.com/browse/PORTALS-1455 for context/details.
> update themesplot config to support new CCP grants

- package.json
- src/configurations/crc-researcher/docTitleConfig.ts
- src/configurations/crc-researcher/headerConfig.tsx
- src/configurations/crc-researcher/logoFooterConfig.ts
- src/configurations/crc-researcher/logoHeaderConfig.ts
- src/configurations/crc-researcher/routeButtonControlWrapperProps.ts
- src/configurations/crc-researcher/routesConfig.ts
- src/configurations/crc-researcher/style/_overides.scss
- yarn.lock
rename and color changes requested by Lynn.
> update to the latest SRC (remove column resizer), update CRC researcher portal to Participant Manager, and remove tab colors

- src/AppInitializer.tsx
- src/_App.scss
- src/configurations/digitalhealth/synapseConfigs/publications.ts
Remove abstract 
also avoid redundant setstate calls
> PORTALS-1475

- package.json
- src/configurations/crc-researcher/routesConfig.ts
- src/portal-components/crc-researcher/ParticipantsBarPlot.tsx
- src/portal-components/index.ts
- src/react-app-env.d.ts
- src/types/portal-config.ts
fed by aggregate query against participant table, using WorkflowState
> CRC issue 593: add an overview participant stacked bar plot.

- package.json
- src/_App.scss
- yarn.lock
make the nav the top level element
> PORTALS-1031

- run.sh
[PORTALS-1479]
Syntax looked OK in test. We'll see...
[PORTALS-1479]: https://sagebionetworks.jira.com/browse/PORTALS-1479
> Add robots.txt

- src/configurations/crc-researcher/routesConfig.ts
> add status line chart to routesConfig

- src/configurations/psychencode/synapseConfigs/data.ts
- src/configurations/psychencode/synapseConfigs/studies.ts
> PORTALS-1506

- run.sh
[PORTALS-1479]
[PORTALS-1479]: https://sagebionetworks.jira.com/browse/PORTALS-1479
> PORTALS-1479: Use Here-Document

- src/configurations/adknowledgeportal/synapseConfigs/publications.ts
- src/configurations/adknowledgeportal/synapseConfigs/studies.ts
- src/configurations/bsmn/routesConfig.ts
- src/configurations/bsmn/synapseConfigs/projects.ts
- src/configurations/bsmn/synapseConfigs/studies.ts
- src/configurations/cancercomplexity/routesConfig.ts
- src/configurations/digitalhealth/synapseConfigs/projects.ts
- src/configurations/digitalhealth/synapseConfigs/studies.ts
- src/configurations/digitalhealth/synapseConfigs/tools.ts
- src/configurations/htan/routesConfig.ts
- src/configurations/nf/organizations.ts
- src/configurations/nf/routesConfig.ts
- src/configurations/nf/synapseConfigs/studies.ts
- src/configurations/psychencode/synapseConfigs/grants.ts
- src/configurations/psychencode/synapseConfigs/studies.ts
- src/portal-components/DetailsPage.scss
- src/portal-components/DetailsPage.tsx
- src/portal-components/index.ts
- src/tests/portal-components/GenerateComponentsFromRow.test.tsx
- src/types/portal-config.ts
- src/types/portal-util-types.ts
I believe that DetailsPage is a more intuitive name than GenerateComponentsFromRow
> Change GenerateComponentsFromRow -> DetailsPage

- src/configurations/adknowledgeportal/synapseConfigs/news.ts
- src/configurations/crc-researcher/routesConfig.ts
- src/configurations/crc-researcher/synapseConfigs/uncategorized.ts
- src/portal-components/crc-researcher/ParticipantsBarPlot.tsx
- src/portal-components/crc-researcher/SurveysCompletedPlots.tsx
- src/portal-components/index.ts
- src/types/portal-config.ts
https://github.com/Sage-Bionetworks/covidrecoverycorps/issues/653
> 653 in CRC researcher portal

- package.json
- src/RouteResolver.tsx
- src/_App.scss
- src/configurations/psychencode/routesConfig.ts
- src/portal-components/Layout.tsx
- src/types/portal-config.ts
- yarn.lock
added alternating home page background and css
bump src - more css tweaks to the people's module
> Home page css tweaks

- src/configurations/crc-researcher/synapseConfigs/tested.ts
- src/configurations/crc-researcher/synapseConfigs/uncategorized.ts
base it on the correct WorkflowState, and remove unavailable testResult column.  also select allSurveysComplete and add a chart for it.
> fix Tested area

- src/configurations/psychencode/routesConfig.ts
This reverts commit 7823cd2de68a71c148918fa581eda98bffb6b233.
> Revert "PORTALS-1619: quick fix to query (Upset plot csql now broken)"

- run.sh
[PLFM-1596] Get UTC date
[PLFM-1596]: https://sagebionetworks.jira.com/browse/PLFM-1596
> Get UTC date

- src/Footer.tsx
- src/Navbar.tsx
- src/_App.scss
- src/configurations/adknowledgeportal/footerConfig.ts
- src/configurations/adknowledgeportal/routesConfig.ts
- src/portal-components/NavLink.tsx
- src/portal-components/Versions.tsx
- src/types/portal-config.ts
Added new routes for ampad
Moved about page link from navbar to footer
Enabled _external_ links from the navbar, wrapped react link component to allow for this.
shortened the max width of the navbar items and wrapped text to handle more navbar links
Altered Versiont.tsx to only fetch build and deploy date once by passing empty array to useEffect
> PORTALS-1612

- src/configurations/crc-researcher/synapseConfigs/uncategorized.ts
> after talking to Lynn, we should only show participants who have completed all surveys

- src/Navbar.tsx
Remove nav-button class that causes the layout issue.
> PORTALS-1519: Remove nav-button class

- src/configurations/psychencode/synapseConfigs/studies.ts
for now use old LIKE (matches amp-ad)
> PORTALS-1633: parser does not parse new HAS clause properly.

- src/configurations/crc-researcher/synapseConfigs/scheduled.ts
- src/configurations/crc-researcher/synapseConfigs/uncategorized.ts
- src/configurations/psychencode/resources.ts
- src/configurations/psychencode/synapseConfigs/studies.ts
(opt for explore 2.0 solution)
> add how_heard and noShow to CRC researcher portal.  revert study details data sql

- package.json
local yarn build succeeded with 2GB
> attempt to increase jenkins executor count to 2

- src/Navbar.scss
- src/portal-components/NavUserLink.tsx
Bug fix per Stockard's comment here: https://sagebionetworks.jira.com/browse/PORTALS-1519?focusedCommentId=120765
> PORTALS-1519: Hide user account arrow down button in mobile

- src/configurations/psychencode/resources.ts
Append versions for release 1!
> append table/view versions

- src/configurations/adknowledgeportal/routesConfig.ts
- yarn.lock
Looks like it updated the yarn.lock file too.
> PORTALS-1659: actually update card titles for human studies

- src/configurations/psychencode/resources.ts
Increments table versions 2. 
Changes include: 
- alphabetized people
- alphabetized grants 
- grants labeled with secondary PI as well as primary
> increment version number to incorporate changes from demo feedback

- src/configurations/psychencode/synapseConfigs/grants.ts
- src/configurations/psychencode/synapseConfigs/studies.ts
This PR: 
- removes fields from search that contain large text
- depends on a search config being added to Explore Data
> customize search

- src/configurations/psychencode/resources.ts
- orders publication cards by author
- fixes duplicates in grant cards 
- fixes NA values in publication cards
- surfaces available data current to today 
- clean up quotations
> update table/view versions for fixes

- src/Markdown.scss
- src/configurations/psychencode/synapseConfigs/studies.ts
- src/portal-components/DetailsPage.scss
1. Fix couple things requested by design: https://sagebionetworks.jira.com/browse/PORTALS-1675?focusedCommentId=121408
2. Add more mobile fixes
> PORTALS-1675: css fixes

- src/configurations/adknowledgeportal/synapseConfigs/studies.ts
- src/portal-components/DetailsPage.tsx
> PORTALS-1212: Change study details page to 2-tab layout

- src/configurations/digitalhealth/synapseConfigs/studies.ts
and it appears to be markdown, so add a label link config to process it
> PORTALS-1718: add dataUsed.

- package.json
- src/configurations/digitalhealth/routesConfig.ts
- src/types/portal-config.ts
- yarn.lock
Hook up TableFeedCards, and update SRC to 1.15.34
> PORTALS-1722

- src/configurations/adknowledgeportal/routesConfig.ts
- src/configurations/adknowledgeportal/synapseConfigs/computational_tools.ts
- src/configurations/adknowledgeportal/synapseConfigs/experimental_tools.ts
- src/configurations/adknowledgeportal/synapseConfigs/projects.ts
- src/configurations/adknowledgeportal/synapseConfigs/publications.ts
linking tools to project details pages, and adding a nav menu to the details page
> PORTALS-1730: config changes for AD portal

- src/configurations/nf/routesConfig.ts
> only show new items

- src/configurations/psychencode/resources.ts
Let's get this versioned view into staging to see how it works!
This PR includes the versioned view that drives the Explore Data and Download list component and includes a fix to the Grants data table.
> Test versioned view with download list in PsychENCODE portal

- src/configurations/psychencode/resources.ts
New data for the PsychENCODE portal. 
Once this PR is merged, the whole site can be pushed to production.
> New table versions for release 1.4

- src/configurations/psychencode/resources.ts
> increment dataSynId

- src/configurations/psychencode/resources.ts
- src/configurations/psychencode/synapseConfigs/studies.ts
- changes study card syntax for sub-title and searchable field
- adds study
> Release 1.6 for new data

- package.json
- yarn.lock
> PORTALS-1841: bump src version to 1.15.70

- src/AppInitializer.tsx
- src/Navbar.tsx
and callback banner background will be white
> PORTALS-1851: use portal header logo (instead of footer logo)

- package.json
- src/configurations/cancercomplexity/synapseConfigs/projects.ts
- src/configurations/nf/organizations.ts
- src/configurations/nf/resources.ts
- src/configurations/nf/routesConfig.ts
- src/configurations/nf/synapseConfigs/funders.ts
- src/configurations/nf/synapseConfigs/index.ts
- yarn.lock
> PORTALS-1854: rework description configuration params, move funders sql into resources.ts

- src/Navbar.tsx
- src/_Core.scss
- src/_Navbar.scss
- src/style/_variables.scss
While looking at the responsive spacing issue for the Explore Bar I found some layout issue on the mobile top nav. Checked with design, the current explorer bar spacing looks good as is. No change is needed. But I did fix the mobile top nav in this jira.
> Portals-1847: Fix Mobile Top Nav

- package.json
- src/configurations/nf/routesConfig.ts
- src/configurations/nf/synapseConfigs/initiatives.ts
- yarn.lock
Still need to release a new SRC and depend on it for this to work.
> PORTALS-1857: update based on design

- package.json
- src/portal-components/NavUserLink.tsx
- yarn.lock
* Addresses PORTALS-1896, PORTALS-1820, PORTALS-1821, PORTALS-1913.
* Avatar size MEDIUM is now what we want in the navbar
> Update SRC to 1.15.93, fix navbar

- src/configurations/nf/routeControlWrapperProps.ts
- src/configurations/nf/routesConfig.ts
- src/configurations/nf/synapseConfigs/hackathons.ts
> PORTALS-1913:  for NF, update Hackathons to Hackathon Projects and include studyLeads

- package.json
- src/Footer.tsx
- yarn.lock
> PORTALS-1924: Add experimental mode button in portals footer

- src/App.scss
- src/RouteControl.tsx
- src/_Core.scss
- src/_ExploreMenu.scss
- src/portal-components/RouteControlWrapper.tsx
- src/style/_variables.scss
> Portals-1875: mobile explore menu

- package.json
- src/AppInitializer.tsx
- src/README.md
- src/configurations/adknowledgeportal/resources.ts
- src/configurations/adknowledgeportal/routesConfig.ts
- src/configurations/adknowledgeportal/synapseConfigs/studies.ts
- src/configurations/crc-researcher/handleParticipantWorkflowChange.tsx
- yarn.lock
> SWC-5589: use access token instead of session token

- package.json
- yarn.lock
> fixes bsmn header card title text color

- src/configurations/adknowledgeportal/resources.ts
We have a new version of the AD Portal all data table for the 18.5 data release.
> update Portal table version

- package.json
- src/AppInitializer.tsx
- src/Navbar.tsx
- src/RouteResolver.tsx
- src/configurations/nf/routesConfig.ts
- src/types/portal-config.ts
- yarn.lock
Add new header nav bar item ShowDownloadV2, which only shows up in alpha mode.  Adjust the user dropdown menu Downloads item to go to this new route (if in alpha mode).
> PORTALS-1948:  Add new Download Cart page to all portals

- src/configurations/nf/resources.ts
Updating to version ~~-4-~~ 5 of fileview. @jay-hodgson - would it be possible to get Triage access to this repository so that I can request a review?
> Update Files fileview version

- src/configurations/nf/routesConfig.ts
Adding the DHART SPORE funder to the grant opportunities module.
> Add DHART SPORE to grant opps module

- package.json
- src/_Core.scss
- yarn.lock
Let's hide the Experimental Mode component in the footer if on mobile (it's extending the viewport)
> Mobile usability issue reported by Google Search Console (about nf, but all sites probably suffer from it)

- src/configurations/adknowledgeportal/resources.ts
Update version of the AD all data file view for the 18.6 data release.
> update AD fileview version

- src/configurations/psychencode/resources.ts
This PR updates the explore studies, publications and data components.
> psychencode portal release 7

- src/configurations/psychencode/resources.ts
> ammend small errors in annotations

- package.json
- yarn.lock
> Upgrade SRC to 2.0.18

- src/configurations/psychencode/resources.ts
This PR includes updates to the Explore Data and Explore Studies components.
> Psychencode release 1.72

- src/configurations/psychencode/resources.ts
> release 1.73

- src/configurations/psychencode/resources.ts
> fix missing annotations

- src/configurations/adknowledgeportal/resources.ts
Point portal to Version 16 of the AD Portal all data file view for the 18.7 (July 2021) data release.
> update AD file view version

- package.json
- yarn.lock
Fixes checkboxes and radio buttons, for example, in the data contribution form in the AD Knowledge Portal
> PORTALS-1970

- package.json
- yarn.lock
[Tracking the same version as SRC](https://github.com/Sage-Bionetworks/Synapse-React-Client/blob/533eeff383fdc89f73aac995080833872573d143/package.json#L160)
> Upgrade TypeScript to v4.3.5

- package.json
- yarn.lock
Fixes env error where old versions of material core conflict with material lab used by SRC
> Upgrade material-ui and SRC

- src/configurations/nf/resources.ts
Updating fileview query to August 30 release (for the NF portal).
> Update fileview to version 6

- src/configurations/psychencode/resources.ts
> new methods

- src/configurations/psychencode/resources.ts
@jay-hodgson Updates the available data table.
> Release 1.8

- src/configurations/nf/resources.ts
Updating NF fileview to v8. Tagging @anngvu just as an FYI: pushing some other changes from staging -> production on the portal so I updated to today's version of the portal fileview so that gets included in the update.
> Update to version 8

- src/configurations/adknowledgeportal/resources.ts
This version corresponds to the 18.10 data release.
> update AD Portal file view version

- src/configurations/nf/resources.ts
This will bring in v9 of the NF portal fileview that has the `Resource_id` data available.
> Update to v9 NF fileview.

- src/configurations/nf/footerConfig.ts
Changing to mail to our preferred contact email address.
> Change contact info

- src/portal-components/nf/BrowseToolsPage.tsx
Hope this is done correctly... :)
> Change Plasmids/Reagents to Genetic Reagents

- src/configurations/adknowledgeportal/resources.ts
Increment again to include a last-minute data upload in this month's release.
> increment version

- package.json
- src/CookiesNotification.tsx
- yarn.lock
PORTALS-2090
PORTALS-2093
SWC-5904
SWC-5911
SWC-5935
SWC-5929
> update to SRC 2.1.10

- package.json
- src/AppInitializer.tsx
- src/_SynapseRedirectDialog.scss
- src/portal-components/SynapseRedirectDialog.tsx
- yarn.lock
Rework Synapse redirect dialog to use a react bootstrap Modal instead of a MUI Dialog.
Implement way to send the cancel message to AppInitializer in order to clear the redirect URL.
> PORTALS-2096

- package.json
- src/_Core.scss
- yarn.lock
SRC 2.1.16 fixes 
https://sagebionetworks.jira.com/browse/PORTALS-2104
https://sagebionetworks.jira.com/browse/PORTALS-2064
(and https://sagebionetworks.jira.com/browse/SWC-5942)
> PORTALS-2065

- src/configurations/nf/resources.ts
Update to latest snapshot, and also corrects an issue in the previous fileview version where someone, possibly me, had accidentally wiped a bunch of annotations.... 😬
> Update to v24 NF fileview

- src/configurations/adknowledgeportal/resources.ts
- src/configurations/adknowledgeportal/routesConfig.ts
- update fileview version to v25
- change the featured studies on the portal home page
> AD portal 19.3 data release

- src/portal-components/nf/BrowseToolsPage.tsx
- src/portal-components/nf/style/_BrowseToolsPage.scss
Move Browse Tools to the top of the page.
Remove Submit Tool from header.
Update "popular searches" -> "suggested searches"
> quick nf gff browse tools page fixes

- src/configurations/adknowledgeportal/synapseConfigs/studies.ts
(in other words, move the methods section down)
> PORTALS-2151: move acknowledgement section up in study details page

- src/configurations/cancercomplexity/routesConfig.ts
(not String_list), so fix the sql operator
> PORTALS-1883: pubMedId column is now a String column

- package.json
- src/RouteResolver.tsx
- src/configurations/crc-researcher/handleParticipantWorkflowChange.tsx
- src/configurations/nf/synapseConfigs/tools.ts
- yarn.lock
Clean up browser history, and fix typescript issue after update
> SRC 3.0.15 update

- src/configurations/adknowledgeportal/synapseConfigs/target_enabling_resources.ts
> PORTALS-2194

- src/configurations/nf/routesConfig.ts
- src/configurations/nf/synapseConfigs/datasetsV2.ts
- src/portal-components/DetailsPage.tsx
- src/portal-components/RouteControlWrapper.tsx
- src/portal-components/StatefulButtonControlWrapper.tsx
- src/portal-components/injectPropsIntoConfig.ts
- src/tests/portal-components/DetailsPage.test.tsx
- src/types/portal-util-types.ts
Nick helped by refactoring SynapseComponentWithContext into another file for more targeted mocking.
> SWC-6147: added missing test

- src/configurations/cancercomplexity/synapseConfigs/people.ts
This PR implements changes as requested from feedback [here](https://sagebionetworks.slack.com/archives/C4TPRCWAG/p1655414504774709), namely:
* display email address above ORCID
* add "Name" as one of the search fields
> [PORTALS-2217] update People card and search fields

- package.json
- src/_ToggleSynapseObjects.scss
- src/configurations/adknowledgeportal/synapseConfigs/projects.ts
- src/configurations/crc-researcher/handleParticipantWorkflowChange.tsx
- src/portal-components/DetailsPage.tsx
- src/portal-components/crc-researcher/ParticipantsBarPlot.tsx
- src/portal-components/crc-researcher/StatusLineChart.tsx
- src/portal-components/crc-researcher/SurveysCompletedPlots.tsx
- src/portal-components/nf/PopularSearches.tsx
- yarn.lock
update to SRC 3.0.29 and set showNoContentAvailableWhenEmpty to true
> PORTALS-2249

- src/configurations/nf/routesConfig.ts
- Add route that handles rendering the DetailsPage
- Remove configs for routes that just act as links for the Navbar
> PORTALS-2252 - Fix NF Organizations Details Page

- src/configurations/adknowledgeportal/synapseConfigs/studies.ts
- src/configurations/nf/organizations.ts
- src/configurations/nf/synapseConfigs/studies.ts
- src/configurations/psychencode/synapseConfigs/studies.ts
- src/portal-components/DetailsPage/DetailsPageTabs.tsx
- src/tests/portal-components/DetailsPage.test.tsx
- src/types/portal-util-types.ts
Ticket required to create tooltip for Dataset Tabs too. However, currently there is no tab for datasets.
> PORTALS-2240

- package.json
- src/configurations/cancercomplexity/routesConfig.ts
- src/configurations/cancercomplexity/synapseConfigs/consortiaHomePage.ts
- src/portal-components/DetailsPage/DetailsPageTabs.tsx
- src/tests/portal-components/DetailsPage.test.tsx
- yarn.lock
Dependent on SRC release >= 3.0.34
> PORTALS-2269: Add consortia component (Programs) to cancer complexity.

- src/configurations/adknowledgeportal/resources.ts
> increment file view version for data release

- package.json
- public/index.html
- src/portal-components/DetailsPage/DetailsPage.tsx
- src/portal-components/DetailsPage/DetailsPageTabs.tsx
- src/portal-components/DetailsPage/SideNavMenu.tsx
- src/portal-components/Versions.tsx
- src/portal-components/crc-researcher/SurveysCompletedPlots.tsx
- src/portal-components/nf/PopularSearches.tsx
- yarn.lock
* Upgrade SRC to 3.0.35
* Rebuild lockfile
* fix new type errors
* Drop some unneeded dependencies
> PORTALS-2272

- package.json
- src/_Core.scss
- src/configurations/cancercomplexity/style/_style_overrides.scss
- yarn.lock
After fixes to query wrapper plot nav padding:
> PORTALS-2289

- src/AppInitializer.tsx
@nickgros : Brought the sledgehammer instead of the scalpel for this proposed (quick) fix
> PORTALS-2293

- src/configurations/arkportal/routesConfig.ts
> PORTALS-2313: add News navbar link

- src/configurations/adknowledgeportal/routesConfig.ts
- src/configurations/adknowledgeportal/style/_style_overrides.scss
- src/configurations/adknowledgeportal/synapseConfigs/programsHomePage.ts
- src/configurations/arkportal/resources.ts
> Support new program on AD home page

- src/AppInitializer.tsx
> SWC-6294: comments

- src/configurations/arkportal/style/_style_overrides.scss
- src/configurations/arkportal/synapseConfigs/datasets.ts
Requested and approved by Mette and Amelia
> PORTALS-2375: Add acknowledgment statement (markdown) to Dataset details page

- src/configurations/arkportal/style/_style_overrides.scss
- src/configurations/arkportal/synapseConfigs/datasets.ts
Reverts Sage-Bionetworks/portals#879
> Revert "ark portal, change dataset detail page"

- src/configurations/cancercomplexity/synapseConfigs/projects.ts
This PR will add another secondary label to the [Project cards](https://sagebionetworks.jira.com/browse/CPO-432).
> Add investigator as secondary label

- src/configurations/adknowledgeportal/resources.ts
Use latest file view version for 19.11 data release.
> increment AD file view version for data release
