Sage-Bionetworks/portals

app-template/public/index.html
Reverts Sage-Bionetworks/portals#57
This embedded widget caused errors to show up in the console (unsupported svg param values?), which caused some versions of Safari to crash.  Recommend reverting, and either try again with an updated widget from statuspage.io, or write a new component that uses their api.
=> Revert "SWC-4928: add status page incident report widget."

app-template/src/portal-components/QueryWrapperFlattened.tsx, app-template/src/test-configuration/exploreHomeConfiguration/publications.ts, app-template/src/test-configuration/routesConfig.ts, app-template/src/types/portal-config.d.ts, app-template/src/types/portal-util-types.d.ts, configurations/adknowledgeportal/routesConfig.ts, configurations/adknowledgeportal/synapseConfigs/programs.ts, configurations/adknowledgeportal/synapseConfigs/projects.ts, configurations/adknowledgeportal/synapseConfigs/studies.ts, configurations/csbc-pson/routesConfig.ts, configurations/nf/routesConfig.ts, configurations/package.json, configurations/stopadportal/routesConfig.ts, configurations/yarn.lock
This has been an ongoing issue for sometime where the types weren't being respected by typescript. Fixed by importing all the component props from SRC explicitly in the portal-config file. This isn't completely fixed for all the portal components whose types aren't being registered.
There are a few TODOs to remove the ts-ignore comments, once SRC is bumped and pulled into this those won't be needed.
=> fix issues with types being dropped

src/AppInitializer.tsx, yarn.lock
if there's not token then getSessionTokenFromCookie will fail instead of passing back and empty string, fix this by putting the code segment in the try/catch block
=> fix logout issue

src/configurations/adknowledgeportal/synapseConfigs/projects.ts, src/configurations/bsmn/routesConfig.ts, src/portal-components/RouteButtonControlWrapper.tsx
^ notice the buttons don't have the bar chart below, they only link out
^Grant Number is now preset on amp-ad project cards
=> Match mocks for BSMN home page, one more fix for PORTALS-1175

src/configurations/csbc-pson/synapseConfigs/tools.ts
Fixing the column name for tool publication links.
=> update publication secondary label for tool cards

src/configurations/csbc-pson/facetAliases.ts, src/configurations/csbc-pson/synapseConfigs/publications.ts
Minor fix to the publications config so that PubMed links render as
> PUBMED LINK — [**PMID:28053997**](https://www.ncbi.nlm.nih.gov/pubmed/?term=28053997)
instead of...
> PUBMED — **https://www.ncbi.nlm.nih.gov/pubmed/?term=28053997**
=> use markdown formatting for pubmed links; update facet alias

src/configurations/cancercomplexity/synapseConfigs/datasets.ts, src/configurations/cancercomplexity/synapseConfigs/grants.ts, src/configurations/cancercomplexity/synapseConfigs/publications.ts, src/configurations/cancercomplexity/synapseConfigs/tools.ts
Also related to [PORTALS-1389](https://sagebionetworks.jira.com/browse/PORTALS-1389) — cleaning up column names to match latest schemas in Synapse.
=> change 'grant' to 'grantNumber' in explore configs

src/configurations/psychencode/synapseConfigs/studies.ts
I made a [mistake with the schema](https://sagebionetworks.jira.com/wiki/spaces/PEC/pages/844759171/PEC+Studies+Schema) (now updated). We want to also include `dataSubtype` and `assay` variables.
=> update metadata query

run.sh
[PORTALS-1596]
In ./build for staging, pushed along with other files
In . for prod, pushed to root of bucket (should overwrite the file deployed by the S3 sync from staging)
[PORTALS-1596]: https://sagebionetworks.jira.com/browse/PORTALS-1596
=> PORTALS-1596: Add deploy_date.txt file to ./build directory

package.json, src/configurations/psychencode/resources.ts, src/configurations/psychencode/routesConfig.ts, src/configurations/psychencode/synapseConfigs/commonProps.ts, src/configurations/psychencode/synapseConfigs/data.ts, src/configurations/psychencode/synapseConfigs/grants.ts, src/configurations/psychencode/synapseConfigs/people.ts, src/configurations/psychencode/synapseConfigs/publications.ts, src/configurations/psychencode/synapseConfigs/studies.ts, yarn.lock
- restructure psychencode to contain top level file `resources.ts` with table identifiers, allowing portal owners to more easily version the portal by update just that file
- Bump src for bug fixes: fix sql parser encountering versioned synId, fix dataset cards for NF, news feed updates
=> PORTALS-1575

src/Navbar.tsx, src/RouteResolver.tsx, src/_App.scss, src/configurations/adknowledgeportal/routesConfig.ts, src/configurations/bsmn/routesConfig.ts, src/configurations/cancercomplexity/routesConfig.ts, src/configurations/crc-researcher/routesConfig.ts, src/configurations/digitalhealth/routesConfig.ts, src/configurations/htan/routesConfig.ts, src/configurations/nf/routesConfig.ts, src/configurations/psychencode/routesConfig.ts, src/configurations/stopadportal/routesConfig.ts, src/test-configuration/routesConfig.ts, src/types/portal-config.ts
This change removes the `name` prop in the route object and only uses the `to` prop
This simplifies things because it removes the dependency which had `name` equal to the last part of the `to` string in the route object
**Before**
```ts
{
to: 'Explore',
...
routes: [
{
name: 'Studies', // this value had to equal to Studies in 'to' below
to: 'Explore/Studies'
}
]
}
```
**Now**
nested routes build the route by concatenating the `to` prop, e.g.
```ts
{
to: 'Explore',
...
routes: [
{
to: 'Studies' // this points to Explore/Studies
}
]
}
```
In total: this removes a prop, a fragile convention, and is more intuitive.
Other-
The `to` prop must always be defined, however, the `link` prop is an escape that lets a route point to a specific destination (there are a cases where links should point out …
=> Proposal to simplify routing

src/configurations/psychencode/resources.ts
Production site will display the current version of the view as view versions are blocked by [PLFM-6468](https://sagebionetworks.jira.com/browse/PLFM-6468).
=> remove version from view as it breaks download list

src/portal-components/DetailsPage.scss
Align tabs with the text content.
=> PORTALS-1734: Fix tab alignment

src/configurations/adknowledgeportal/synapseConfigs/studies.ts
=> PORTALS-1755: Add study metadata on study details page

src/Navbar.scss
1. Reset menu item height to `auto` instead of 100%
2. Make sure desktop menu to be hidden when in mobile view (need overwrite important from another place)
3. Fix download link and download size alignment in mobile view
=> PORTALS-1797: CSS fixes for mobile top nav

src/configurations/psychencode/resources.ts
Remove redundancy, and reuse `dataSynId`.
=> metadatasql points to datasynid

package.json, src/configurations/adknowledgeportal/synapseConfigs/studies.ts, yarn.lock
Also filter the facets (for left-hand facet value navigation).
=> PORTALS-1803: change AD metadata table to use explore 2.0, but hide visualizations by default.

src/configurations/psychencode/routesConfig.ts
My goal is to keep the content the same but point to a wiki sub-page, instead of the Project wiki main page.
=> new about page wiki

src/_Core.scss
supposedly fixed, but I'm seeing it as 1% in the output bundle.
https://github.com/facebook/create-react-app/issues/7980
=> work around opacity percentage bug during bundle creation

src/configurations/nf/routesConfig.ts
Changing the NF portal header link "Docs" to "Help" and changing the link from the github.io docs site to the new confluence docs site. I think I've changed this in the only place it needs to be changed, but I don't _really_ know what I'm doing, and I have no ability to test locally. :)
=> Change Docs link

src/_Navbar.scss
Remove extra border-radius style inherited from .btn css for mobile nav menu.
=> Portals-1875: extra border radius

package.json, src/AppInitializer.tsx, src/Navbar.tsx, src/RouteResolver.tsx, src/portal-components/DetailsPage.tsx, src/portal-components/csbc-home-page/AboutPortal.tsx, src/portal-components/csbc-home-page/Ecosystem.tsx, src/portal-components/csbc-home-page/HomePageCard.tsx, src/portal-components/csbc-home-page/HomePageCardContainer.tsx, src/tests/RouterResolver.test.tsx, src/tests/portal-components/RouteButtonControlWrapper.test.tsx, src/types/portal-util-types.ts, yarn.lock
Depends on https://github.com/Sage-Bionetworks/Synapse-React-Client/pull/1047
Will need an update to SRC to get those changes
=> SWC-5612 - Use SynapseContextProvider so SRC components receive token via context

src/configurations/nf/synapseConfigs/studies.ts
added ` 'grantDOI'` to study card metadata values and added it to the 'searchable' list.
=> add grant DOI to study card

src/RouteControl.tsx, src/_Core.scss
Make the tab scroll button icons slightly bigger and apply the portals accent color
=> Style tweaks

src/configurations/psychencode/resources.ts
This PR: 
- increments the version for all views (people, grants, publications, studies and data).
- replaces the metadata query to use resourceType to match the way the AD portal is managed.
=> portal release 1.82

src/configurations/nf/synapseConfigs/tools.ts
I made this change to the config in order to add these new secondaryLabels to the biobank cards on the portal (https://staging.nf.synapse.org/Explore/Tools/DetailsPage?resourceId=e4e60a43-9073-4dfa-a629-76b472451b7f).
=> Add biobank secondaryLabels

src/configurations/cancercomplexity/footerConfig.ts
From Slack:
> @aclayton555: [csbc_pson_dcc@sagebase.org] is the google group contact listed on the CCKP. It looks like this group currently has 1 member, but I can't see who it is...
Regardless, I would propose updating this to our active google group [sage-csbc-pson@sagebase.org](mailto:sage-csbc-pson@sagebase.org) (me, Amber, Julie).
=> Update mailing address for CCKP Contact Us form

src/configurations/cancercomplexity/routesConfig.ts, src/configurations/cancercomplexity/synapseConfigs/tools.ts
The CSBC/PS-ON team would like to display more information for the Tool components, now that we have transitioned over to a new schema.
Notable changes:
* New labels found on a Tool card
* Clicking on a Tool card now redirects to a Tool Details page (rather than redirecting to the tool itself)
Some whitespace were also removed (via autoformatter).
[Related JIRA ticket](https://sagebionetworks.jira.com/browse/CPO-10)
=> Tool cards and details update

craco.config.js, package.json, src/Navbar.tsx, src/tests/RouterResolver.test.tsx, src/tests/portal-components/RouteButtonControlWrapper.test.tsx, yarn.lock
* Bump react-scripts
* Add craco, browser polyfills
While craco isn't currently actively maintained, I think it's still worth using it to upgrade to react-scripts v5. We may be able to just use plain react-scripts in the future, depending on whether https://github.com/facebook/create-react-app/pull/11764 (or similar PR) is merged.
=> Bump react-scripts to v5

src/_Core.scss
=> fix user dropdown menu position

src/configurations/cancercomplexity/routesConfig.ts
I noticed as I was poking around the portal that using values with commas in them as the key between tables result in unexpected behavior, e.g. [this grant](https://cancercomplexity.synapse.org/Explore/Grants/DetailsPage?grantId=syn17084053) and its related projects:
I'm guessing the two commas in the grant name is causing the query to mistake there being three "values" to search for instead of one.  After updating the config to use grant number instead of grant name, the text blurb now only shows up once:
=> Update columnName and tableSqlKeys in CCKP's Grant Details page

src/configurations/cancercomplexity/synapseConfigs/people.ts
From @aclayton555 :
> * I personally feel that we should remove the "Synapse Profile Link" from the People cards in the explore module because (IMO) it tricks you into clicking on that profile, instead of navigating to the People details page/profile. Within the People Details page, I would also order the Synapse profile link after ORCID, Grant name and Consortium.
> * Now I am thinking that we shouldn't show Chair roles at all (because this will be "none" for a lot of people), and instead show the Working Group Participation data if that is possible? I think would be more meaningful
=> implement feedback from team regarding people cards

src/configurations/cancercomplexity/routesConfig.ts
We added some data to the tables and after some spot-checking, I noticed that some of the cards were not mapping as expected.  The following changes will fix the bugs:
**Publications card - single quotes**
Before | After
:---|:---
**Publications card - commas**
Before | After
:---|:---
**Tools card**
Before | After
:---|:---
=> bug fixes with routing on some cards

src/configurations/cancercomplexity/routesConfig.ts
Requested by @aclayton555 :
> also wondering is if the Grant Name on the People Details pages can also link to the respective Grant Details page - similar to how Publications, etc Details pages do?
QC'd on my end and everything looks okay so far!
**Screenshots**
=> add mapping from People -> Grant

src/portal-components/DetailsPage/DetailsPage.tsx, src/portal-components/DetailsPage/DetailsPageTabs.tsx, src/portal-components/DetailsPage/SideNavMenu.tsx, src/portal-components/DetailsPage/utils.ts
- Clicking the link copies the URL to the section instead of navigating to it
- Fix an issue where the DetailsPageTab redirect would break navigating between tabs.
- Fix ID mismatch between SideNavMenu and rendered sections
Clip of "Copy link" functionality:
https://user-images.githubusercontent.com/17580037/180071249-4cbf5bdd-241e-4845-b51c-041283b6fe6c.mov
=> PORTALS-2228 - "Copy link" and fix redirect

src/configurations/nf/routesConfig.ts
- Rename "Hackathon Projects" route to "Hackathon" to match Details Page routing
- Redirect "/Explore/Hackathon Projects" to "/Explore/Hackathon"
=> PORTALS-2277

src/_Core.scss
Pointing out the current issue:
=> Total query results padding

src/configurations/cancercomplexity/routeControlWrapperProps.ts, src/configurations/cancercomplexity/routesConfig.ts, src/configurations/cancercomplexity/synapseConfigs/datasets.ts, src/configurations/cancercomplexity/synapseConfigs/publications.ts
This PR addresses this [Jira ticket](https://sagebionetworks.jira.com/browse/CPO-328), specifically:
* Removing "Files" from the navigation bar and dropdown menu
* Replacing the table of data files in a Datasets Details Page with "Related *" cards
* Adding/removing secondary items to the Publications and Datasets cards (to make the cards as consistent as possible)
=> CPO-328: Remove FILES from CCKP + card related updates

src/configurations/cancercomplexity/synapseConfigs/people.ts
In the Person card, we have `Grant Name` as one of the secondary labels, which is redundant with the "Related Grants" information on the details page.  Ergo, we'd like to remove the secondary label.
=> Remove secondary label to avoid redundancy

src/configurations/cancercomplexity/routesConfig.ts, src/configurations/cancercomplexity/synapseConfigs/tools.ts
From @aclayton555 :
> Hey there, I was poking around the CCKP in some of our recently added grants and noted that there seems to be a display issue with the "Related Tools" section on at least a couple of them. See example: https://www.cancercomplexity.synapse.org/Explore/Grants/DetailsPage?grantId=syn35270534#RelatedTools
I realize it's because I forgot to make some updates to the routes config after we switched to the new tools table.
In addition to the bug fix above, I also updated the related items routing to use `grantNumber` in general instead of `grantName`, since commas in the grant names result in multiple queries (thus resulting in duplicate cards), e.g. [Mechanical determinants of organ-selective metastatic colonization, dormancy and …
=> Grant name bug fix

src/configurations/arkportal/synapseConfigs/data.ts, src/configurations/arkportal/synapseConfigs/datasets.ts, src/portal-components/DetailsPage/DetailsPage.tsx, src/types/portal-util-types.ts
this will show an error if the snapshot does not exist, which should tell the portal owner to lock down the data so that it can be downloaded
=> PORTALS-2439: always attempt to pull in snapshot in detail page
